apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  labels:
    app: quotes
    version: "1"
    tier: backend
spec:
  type: NodePort
  selector:
    app: quotes
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
