apiVersion: v1
kind: ReplicationController
metadata:
  name: portal
  labels:
    app: portal
    version: "1"
    tier: frontend
spec:
  replicas: 2
  selector:
    app: portal
    version: "1"
  template:
    metadata:
      labels:
        app: portal
        version: "1"
        tier: frontend
    spec:
      containers:
      - name: portal
#       FOR DEPLOY FROM DOCKERHUB
#        image: portal:1
        image: magnuslarsson/portal:1
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
